### ISSUE TITLE
KeyError on making migrations

### ISSUE THREAD

**Issue by eriktelepovsky** [SmileyChris/django-countries#160]
Hi, I am running into this issue using:

Python 3.5.2
django-countries==4.0
Django==1.10.3

```python
class User(AbstractUser):
    ...
    country = CountryField()
```

```
python manage.py makemigrations
```

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    ProjectState.from_apps(apps),
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/db/migrations/state.py", line 188, in from_apps
    model_state = ModelState.from_model(model)
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/db/migrations/state.py", line 374, in from_model
    fields.append((name, field.clone()))
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 457, in clone
    name, path, args, kwargs = self.deconstruct()
  File "/Users/erik/env/giaroo/lib/python3.5/site-packages/django_countries/fields.py", line 253, in deconstruct
    kwargs.pop('choices')
KeyError: 'choices'
```

Any help is appreciated. Thank you.

**Comment by eriktelepovsky** [comment]
I have created minimal Django project and it worked fine. Issue was in my project. I was overriding "makemigrations" command with my custom implementation (to ignore some field options like verbose_name, help_text etc).
