### ISSUE TITLE
multiple=True prevents blank option

### ISSUE THREAD

**Issue by danielquinn** [SmileyChris/django-countries#197]
In my local project, I've got a field defined like so:

```python
# models.py
class User(models.Model):
    ...
    countries = CountryField(multiple=True)

# forms.py
class MyForm(forms.ModelForm):

    class Meta:
        model = User

    ...

    countries = forms.MultipleChoiceField(
        choices=countries,
        widget=FilteredSelectMultiple("countries", is_stacked=False),
        required=False
    )
```

In cases where `countries` is empty at first (`""`), this works well to allow me to assign multiple countries to that field.  I can also change which countries are assigned to the user without issue.  *However*, if I want this field to be blank, ie, no countries, `[]`, then this silently fails.  I can remove all countries from the list, hit submit in the admin, and my update is ignored: whatever was in `countries` before is still there.

If I forgo the use of `forms.MultipleChoiceField`, the default is a simple multi-select box with no `---` option, so I figure this must be an issue with how blank options are handled in this module.

I have a feeling that this is related to #191 but after a lot of digging through both this project's code and Django's, I couldn't find a useable work around.  It seems reasonable to me though that a `multiple=True` field should allow for no countries.

If I've misunderstood how to use django-countries in this case, I'd appreciate some pointers, but if I haven't missed anything, then I think this is a bug.

**Comment by SmileyChris** [comment]
I just set up a sandbox project to test this out. The simple multi-select box works fine. You don't get a '---' option on purpose -- unselecting every country and saving works fine.

**Comment by SmileyChris** [comment]
Additionally, using the FilteredSelectMultiple widget on a custom form for admin also worked fine. Removing the countries and saving worked fine.

**Comment by danielquinn** [comment]
You're absolutely right.  I think this all happened because I tried to add `blank=True` to the model field definition and when I tried to make a migration and then actually run it, everything exploded:

```
  Applying users.0003_auto_20170804_1235...Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "virtualenv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/schema.py", line 113, in _alter_field
    new_db_params, strict,
  File "virtualenv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 566, in _alter_field
    old_default = self.effective_default(old_field)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 211, in effective_default
    default = field.get_db_prep_save(default, self.connection)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 710, in get_db_prep_save
    prepared=False)
  File "virtualenv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 702, in get_db_prep_value
    value = self.get_prep_value(value)
  File "virtualenv/src/django-countries/django_countries/fields.py", line 307, in get_prep_value
    country_to_text(code) for code in value if country_to_text(code))
TypeError: 'NoneType' object is not iterable
```

At that point, I think I got it in my head that blank=True wasn't going to work and so I feel down a rabbit hole of trying to *make* it work :-(

After seeing your message here, I took a step back and tried to just add `blank=True` again, saw the same error in migration again, and decided to work around it by:

* Creating a new column
* Copying the values into said column
* Dropping the old column
* Renaming the new column to the old name

Now, `blank=True` appears to work just fine as you'd expect.  I'm sorry for the confusion.  I'm not sure if this migration thing is a known issue or if *that's* a bug, but I leave that to you to decide.
