### ISSUE TITLE
value too long for type character varying(2)

### ISSUE THREAD

**Issue by Borkason** [SmileyChris/django-countries#218]
An exception is thrown when trying to assign a alpha-3 code to a country field. But assignment and country are correctly recognized. See `a.land = 'usa'` in the below example.

```python
>>> a = Abonnent.objects.first()
>>> a.save()
>>> a
<Abonnent: Abonnent object (374713)>
>>> a.land
Country(code='DE')
>>> a.land.name
'Deutschland'
>>> a.land = 'ch'
>>> a.save()
>>> a.land
Country(code='ch')
>>> a.land.name
'Schweiz'
>>> a.land = 'usa'
>>> a.land
Country(code='usa')
>>> a.land.name
'Vereinigte Staaten von Amerika'
>>> a.save()
Traceback (most recent call last):
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: FEHLER:  Wert zu lang für Typ character varying(2)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\base.py", line 823, in _save_table
    forced_update)
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\sql\compiler.py", line 1374, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\...\myproject_venv\lib\site-packages\django\db\models\sql\compiler.py", line 1063, in execute_sql
    cursor.execute(sql, params)
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\...\myproject_venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\...\myproject_venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: FEHLER:  Wert zu lang für Typ character varying(2)
```

A similar issue was reported in #198.

**Comment by Borkason** [comment]
Is it possible that this is related to #209?

**Comment by SmileyChris** [comment]
Yep, this should work fine in master.

**Comment by Borkason** [comment]
Looks good, does not raise errors anymore.

**Comment by yuquant** [comment]
你的字符串设置的最大长度有问题
There must be something wrong in your model about the max_length of the CharFiled .For example
```
_gender = models.CharField(choices=(('male', u'男'),('female', u'女')), verbose_name=u'性别', default='male', max_length=1)
gender = models.CharField(choices=(('male', u'男'),('female', u'女')), verbose_name=u'性别', default='male', max_length=6)_
```
The first example is wrong.
