### ISSUE TITLE
Compat with Django 2.2

### ISSUE THREAD

**Issue by srtab** [SmileyChris/django-countries#264]
Hi,
I'm having problems when i try to use django-countries with Django 2.2. Here's the traceback:

```
Traceback (most recent call last):
  File "runtests.py", line 12, in <module>
    django.setup()
  File "/app/.tox/py36-djangomaster/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/app/.tox/py36-djangomaster/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/app/.tox/py36-djangomaster/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/app/.tox/py36-djangomaster/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/.tox/py36-djangomaster/lib/python3.6/site-packages/django_countries/__init__.py", line 7, in <module>
    from django.utils import six
ImportError: cannot import name 'six'
```
Are there any plans to make django-countries compatible with Django 2.2?

Tks

**Comment by hsmett** [comment]
Hello @srtab !
It's been a month since Django 2.2 came out.
I made a pull request to test django-countries with Django 2.2, and everything seems to work fine:
https://github.com/SmileyChris/django-countries/pull/257

You are actually working with the django master branch here, which is moving quickly! :)

I think you should either avoid to test your application with django master, or allow failures for this tox target.

Hugo

**Comment by srtab** [comment]
@hsmett You're absolutely right, i forgot i was testing against Django master and not Django 2.2. 

That's exactly what i'm doing, tests against Django master are only complementary with failure allowance.

Tks
