### ISSUE TITLE
no_translation_fallback eventually overwrites default fallback to empty when under the server is under high load

### ISSUE THREAD

**Issue by xi-business** [SmileyChris/django-countries#404]
The function `no_translation_fallback` defined [here](https://github.com/SmileyChris/django-countries/blob/master/django_countries/__init__.py#L57-L68) is used to override the default translation fallback (identity) to empty within a `with` block and then to restore the original value. Normally everything is okay, but when the server is under high load, a race condition may occur.

What happens is more or less:
1. catalog._fallback initialized to Default
2. catalog._fallback = A; orig = Default
3. catalog._fallback = B; orig = A # Problem starts here
4. catalog._fallback = Default (from 2)
5. catalog._fallback = A (from 3)
6. catalog._fallback is now A instead of Default when idle.

To fix this, `no_translation_fallback` needs some kind of mutex or needs to be reworked so that it is not swapping a global variable to local scope and back like that.

This bug first appeared in 7.4.0 with the introduction of `no_translation_fallback`. Actually, why is even `no_translation_fallback` needed instead of the default identity?

The bug can be reproduced by adding some slow debug code to the function and concurrently requesting sites from a django server that uses django-countries. I debugged it by changing the function to the following:
```python3
@contextmanager
def no_translation_fallback():
    if not settings.USE_I18N:
        yield
        return
    catalog = _trans.catalog()
    original_fallback = catalog._fallback
    catalog._fallback = EmptyFallbackTranslator()

    import sys
    print(f'!!!!! REPLACED FALLBACK from {id(original_fallback)} to {id(catalog._fallback)}', file=sys.stderr)
    import traceback
    traceback.print_stack()

    try:
        yield
    finally:
        print(f'!!!!! RESTORING FALLBACK {id(original_fallback)} to {id(catalog._fallback)}', file=sys.stderr)
        catalog._fallback = original_fallback
```

The log I got was (comments after # are my edit):
```
# ...
!!!!! RESTORING FALLBACK 140706581130456 to 3051452141680
# Note that 140706581130456 is the original
!!!!! REPLACED FALLBACK from 140706581130456 to 3051452141680
# ...
!!!!! RESTORING FALLBACK 140706581130456 to 3051452141680
!!!!! REPLACED FALLBACK from 140706581130456 to 3051452141680
# ... (a few dozen of requests)
!!!!! RESTORING FALLBACK 140706581130456 to 3051501356656
2022-11-04 03:35:05,478 [INFO-D] "GET /ajax/sync/?_=1667528209942 HTTP/1.1" 200 41
!!!!! REPLACED FALLBACK from 140706581130456 to 3051497763456
# Note that the second replacing thinks that 3051497763456 is the original
!!!!! REPLACED FALLBACK from 3051497763456 to 3051500062704 

  File "C:\...\pydev_monkey.py", line 798, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "C:\Python39\lib\threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\...\venvs\lib\site-packages\django\core\servers\basehttp.py", line 204, in handle
    self.handle_one_request()
  File "C:\...\venvs\lib\site-packages\django\core\servers\basehttp.py", line 227, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Python39\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\...\venvs\lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\middleware.py", line 58, in __call__
    response = toolbar.process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\timer.py", line 65, in process_request
    return super().process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\headers.py", line 46, in process_request
    return super().process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\template_profiler_panel\panels\template.py", line 250, in process_request
    response = super(TemplateProfilerPanel, self).process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\whitenoise\middleware.py", line 60, in __call__
    response = self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\...\venvs\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\...\django_project\django_app\views.py", line 185, in dispatch
    request.user.full_clean()
  File "C:\...\venvs\lib\site-packages\django\db\models\base.py", line 1445, in full_clean
    self.clean_fields(exclude=exclude)
  File "C:\...\venvs\lib\site-packages\django\db\models\base.py", line 1497, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "C:\...\venvs\lib\site-packages\django\db\models\fields\__init__.py", line 755, in clean
    self.validate(value, model_instance)
  File "C:\...\venvs\lib\site-packages\django_countries\fields.py", line 412, in validate
    return super().validate(value, model_instance)
  File "C:\...\venvs\lib\site-packages\django\db\models\fields\__init__.py", line 727, in validate
    for option_key, option_value in self.choices:
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 347, in __iter__
    countries = tuple(
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 275, in translate_code
    yield self.translate_pair(code, name)
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 295, in translate_pair
    with no_translation_fallback():
  File "C:\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 68, in no_translation_fallback
    traceback.print_stack()
!!!!! RESTORING FALLBACK 140706581130456 to 3051500062704
!!!!! REPLACED FALLBACK from 140706581130456 to 3051500062704
  File "C:\...\pydev_monkey.py", line 798, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "C:\Python39\lib\threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\...\venvs\lib\site-packages\django\core\servers\basehttp.py", line 204, in handle
    self.handle_one_request()
  File "C:\...\venvs\lib\site-packages\django\core\servers\basehttp.py", line 227, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Python39\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\...\venvs\lib\site-packages\django\contrib\staticfiles\handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\wsgi.py", line 131, in __call__
    response = self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\middleware.py", line 58, in __call__
    response = toolbar.process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\timer.py", line 65, in process_request
    return super().process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\headers.py", line 46, in process_request
    return super().process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\template_profiler_panel\panels\template.py", line 250, in process_request
    response = super(TemplateProfilerPanel, self).process_request(request)
  File "C:\...\venvs\lib\site-packages\debug_toolbar\panels\__init__.py", line 206, in process_request
    return self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\whitenoise\middleware.py", line 60, in __call__
    response = self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = response or self.get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\...\venvs\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\...\venvs\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\...\django_project\django_app\views.py", line 185, in dispatch
    request.user.full_clean()
  File "C:\...\venvs\lib\site-packages\django\db\models\base.py", line 1445, in full_clean
    self.clean_fields(exclude=exclude)
  File "C:\...\venvs\lib\site-packages\django\db\models\base.py", line 1497, in clean_fields
    setattr(self, f.attname, f.clean(raw_value, self))
  File "C:\...\venvs\lib\site-packages\django\db\models\fields\__init__.py", line 755, in clean
    self.validate(value, model_instance)
  File "C:\...\venvs\lib\site-packages\django_countries\fields.py", line 412, in validate
    return super().validate(value, model_instance)
  File "C:\...\venvs\lib\site-packages\django\db\models\fields\__init__.py", line 727, in validate
    for option_key, option_value in self.choices:
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 347, in __iter__
    countries = tuple(
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 275, in translate_code
    yield self.translate_pair(code, name)
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 295, in translate_pair
    with no_translation_fallback():
  File "C:\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\...\venvs\lib\site-packages\django_countries\__init__.py", line 68, in no_translation_fallback
    traceback.print_stack()
# This is where the bug occurs - from now on 3051497763456 is the default fallback
!!!!! RESTORING FALLBACK 3051497763456 to 3051500062704

# All hell breaks loose here...
```

**Comment by SmileyChris** [comment]
This *should* be fixed by the above commit. I haven't rolled a release yet - do you think you could try this against the master branch before I do?

**Comment by MDziwny** [comment]
I think I have a similar issue, I've tried to test it to check if it solves the issue but the fix doesn't work with python 3.10

**Comment by SmileyChris** [comment]
@MDziwny you're running the latest `master` branch and are still encountering the error?

**Comment by SmileyChris** [comment]
> Actually, why is even `no_translation_fallback` needed instead of the default identity?

This is needed due to the fact that we have partial translations and old names/common names.

Take into account the recent name change of Türkiye -- while a translation doesn't have this string translated, it should fall back to the translation of "old name" Turkey. Without this custom translation catalog there is no way to tell if a translation has provided a translation string (previously it just checked to see if the translated string matched the base English string, but see #364 for why that doesn't work).

**Comment by xi-business** [comment]
I reviewed the code and you're permanently overwriting whatever fallback was there before with yours which wraps the gettext one. If I am not mistaken, you're basically removing the functionality of replacing it by other libs/apps.
I'll get back to you once I run some tests on my software.

**Comment by SmileyChris** [comment]
> you're permanently overwriting whatever fallback was there before with yours

That's what I thought too when writing the code, and had actually added the original _fallback (via .add_fallback). It seems logical, but causes a recursion error when trying to resolve a translation 😕.

**Comment by xi-business** [comment]
Can you further describe the problem why is `no_translation_fallback` needed?

Can you tell me where exactly in the code are you trying to translate a string in multiple ways, using old names and so on as described above? I'll try to think of another solution that does not change gettext internals and does not have a potential to cause conflicts with other packages.

**Comment by MDziwny** [comment]
> @MDziwny you're running the latest `master` branch and are still encountering the error?

I tried to use the latest version of the master branch and I've got this error:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.10/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1284, in check
    *cls._check_fields(**kwargs),
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1395, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1012, in check
    *super().check(**kwargs),
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 199, in check
    *self._check_choices(),
  File "/usr/local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 265, in _check_choices
    if not all(
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 135, in __wrapper__
    res = func(*self.__args, **self.__kw)
  File "/usr/local/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 94, in gettext
    return _trans.gettext(message)
  File "/usr/local/lib/python3.10/site-packages/django/utils/translation/trans_real.py", line 358, in gettext
    result = translation_object.gettext(eol_message)
  File "/usr/local/lib/python3.10/gettext.py", line 501, in gettext
    return self._fallback.gettext(message)
  File "/usr/local/lib/python3.10/site-packages/django_countries/__init__.py", line 59, in gettext
    if translation_state.fallback:
AttributeError: '_thread._local' object has no attribute 'fallback'
```

**Comment by xi-business** [comment]
I performed the testing. I got the same error. I am not sure what kind of threading django uses internally, but I think that
```python3
translation_state.fallback = True
```
is only called by the initial thread before fork. For now I made a very dirty fix and debug modifications:
```python3
class EmptyFallbackTranslator(NullTranslations):
    def gettext(self, message: str) -> str:
        if not hasattr(translation_state, 'fallback'):
            translation_state.fallback = True
        if translation_state.fallback:
            return super().gettext(message)
        return ""
```
```python3
@contextmanager
def no_translation_fallback():
    if not settings.USE_I18N:
        yield
        return
    # Ensure the empty fallback translator has been installed.
    catalog = _trans.catalog()

    import sys
    import traceback
    traceback.print_stack()
    if not hasattr(translation_state, 'fallback'):
        translation_state.fallback = True
    print(f'[DEBUG] BEFORE no_translation_fallback: {id(catalog._fallback)}/{translation_state.fallback}', file=sys.stderr)
    if not isinstance(catalog._fallback, EmptyFallbackTranslator):
        catalog._fallback = empty_fallback_translator
    # Set the translation state to not use a fallback while inside this context.
    translation_state.fallback = False
    print(f'[DEBUG] DURING no_translation_fallback: {id(catalog._fallback)}/{translation_state.fallback}', file=sys.stderr)
    try:
        yield
    finally:
        translation_state.fallback = True
        print(f'[DEBUG] AFTER no_translation_fallback: {id(catalog._fallback)}/{translation_state.fallback}', file=sys.stderr)
```

I have tested it for a while against master (ad3df3e7893bbf70ae233854db509ff76103f336) without encountering any problems so far. However, these fixes are extra ugly and the problem of compatibility with anything that uses fallbacks remains.

Assuming that fallbacks will be sacrificed, why not just replace the gettext fallback at the beginning before `no_translation_fallback` is called and process forked? I also suggest documenting somewhere this potentially breaking change of replacing fallbacks if no better solution is found.

**Comment by SmileyChris** [comment]
Ok, this latest commit should do a better job, retaining existing fallbacks.

**Comment by SmileyChris** [comment]
> Can you further describe the problem why is no_translation_fallback needed?
> 
> Can you tell me where exactly in the code are you trying to translate a string in multiple ways, using old names and so on as described above? I'll try to think of another solution that does not change gettext internals and does not have a potential to cause conflicts with other packages.

A country can have a shadowed name of the full ISO name when using *common names*, or because there's an *old name*.

The German translation has a common name of "Venezuela", but it's the same as English, and the original method before 7.4 just stupidly assumed if your text came back the same as English then you didn't have a translation. Hence in German, you'd never get this common name and they only ever got: "Venezuela (Bolivarische Republik)".

The German translation doesn't yet have a translation for the new name "Türkiye", but does for its equivalent old name of "Turkey": "Türkei". Again, we need to know that German doesn't have the new name in its catalog directly, which gettext doesn't give us a way to do (it'll just use the en_us fallback).

**Comment by xi-business** [comment]
```from asgiref.local import Local```
Will this work with asgi, i.e., the documented way to run Django with Apache2?

**Comment by xi-business** [comment]
https://github.com/SmileyChris/django-countries/commit/e2f4e408d9a9e9617d4738199fc5c8b313b0e40c#diff-40c00e73ac4f64fab42d1fa66c6a7fea31dd84d5e67f649b2d9cc182578e108cR74-R77
You can have a race condition here in which the fallback will become `EmptyFallbackTranslator`. Thread switch may happen between lines 75 and 76. Since you're replacing fallback anyway, why not do it outside (in the initialization phase) before fork? Or why not introduce a mutex/condition if this has to go there?

**Comment by MDziwny** [comment]
> Ok, this latest commit should do a better job, retaining existing fallbacks. Could you have another go at breaking it please? 🙏🏻

I've tried and it's now working fine on python 3.10 (but @xi-business has few good remarks).

**Comment by SmileyChris** [comment]
Thanks for the review

> You can have a race condition here in which the fallback will become `EmptyFallbackTranslator`. Thread switch may happen between lines 75 and 76.

I don't see the race condition. The original_fallback variable was set before and a thread switch won't matter after that. Worst case is that two instances are generated and only one is set.

> Since you're replacing fallback anyway, why not do it outside (in the initialization phase) before fork?

The active catalog can change across threads, it needs to be checked each time to ensure the active catalog has the empty fallback installed.

> Or why not introduce a mutex/condition if this has to go there?

Share some code if you can see a better ready that I'm missing...

**Comment by MDziwny** [comment]
I don't know if it can be of any help, but I've seen a similar change recently in `django-modeltranslation`: https://github.com/deschler/django-modeltranslation/pull/657/files

**Comment by SmileyChris** [comment]
I think we're in a much better place. It seems that we have confirmation of things working. I'm going to consider this fixed, but feel free to keep the discussions or investigations going :)

We can open a new ticket if anything new comes to light.

**Comment by MDziwny** [comment]
Is it planned to soon release this fix in a new release?

**Comment by SmileyChris** [comment]
Sorry for the delay, 7.5 is out now
