### ISSUE TITLE
django_countries 7.5 missing dependency on asgiref

### ISSUE THREAD

**Issue by terceiro** [SmileyChris/django-countries#410]
```
$ virtualenv /tmp/countries
created virtual environment CPython3.10.9.final.0-64 in 289ms
  creator CPython3Posix(dest=/tmp/countries, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/terceiro/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.5.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
$ . /tmp/countries/bin/activate
$ pip install django_countries
Collecting django_countries
  Downloading django_countries-7.5-py3-none-any.whl (842 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 843.0/843.0 kB 1.3 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, django_countries
Successfully installed django_countries-7.5 typing-extensions-4.4.0
$ python -c 'import django_countries'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/countries/lib/python3.10/site-packages/django_countries/__init__.py", line 22, in <module>
    from asgiref.local import Local
ModuleNotFoundError: No module named 'asgiref'
```

**Comment by SmileyChris** [comment]
Does look like that should be a dependency. PR welcome if you have the time/ability!
