### ISSUE TITLE
Uses Deprecated package since Django 3.0(django.utils.six)

### ISSUE THREAD

**Issue by chilusoft** [SmileyChris/django-countries#437]
Everything was running smooth until I tried running the project but got his Traceback

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django_countries/__init__.py", line 7, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/data/apps/trialplanner/venvs/backend-v4jkIZyP/lib/python3.10/site-packages/django/utils/__init__.py)
```

**Comment by SmileyChris** [comment]
Latest released version no longer uses `django.utils.six`
